//go:build !ignore_autogenerated

/*
Copyright 2026 VileEnd.

Licensed under the MIT License. See the LICENSE file in the repository root
for the full license text.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationGatewayGuidance) DeepCopyInto(out *ApplicationGatewayGuidance) {
	*out = *in
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]ListenerGuidance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationGatewayGuidance.
func (in *ApplicationGatewayGuidance) DeepCopy() *ApplicationGatewayGuidance {
	if in == nil {
		return nil
	}
	out := new(ApplicationGatewayGuidance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSourceSpec) DeepCopyInto(out *CertificateSourceSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSourceSpec.
func (in *CertificateSourceSpec) DeepCopy() *CertificateSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverySpec) DeepCopyInto(out *DiscoverySpec) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(bool)
		**out = **in
	}
	if in.HTTPRoutes != nil {
		in, out := &in.HTTPRoutes, &out.HTTPRoutes
		*out = new(bool)
		**out = **in
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = new(bool)
		**out = **in
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverySpec.
func (in *DiscoverySpec) DeepCopy() *DiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(DiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuerReference) DeepCopyInto(out *IssuerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuerReference.
func (in *IssuerReference) DeepCopy() *IssuerReference {
	if in == nil {
		return nil
	}
	out := new(IssuerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultCertificateSync) DeepCopyInto(out *KeyVaultCertificateSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultCertificateSync.
func (in *KeyVaultCertificateSync) DeepCopy() *KeyVaultCertificateSync {
	if in == nil {
		return nil
	}
	out := new(KeyVaultCertificateSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyVaultCertificateSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultCertificateSyncList) DeepCopyInto(out *KeyVaultCertificateSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyVaultCertificateSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultCertificateSyncList.
func (in *KeyVaultCertificateSyncList) DeepCopy() *KeyVaultCertificateSyncList {
	if in == nil {
		return nil
	}
	out := new(KeyVaultCertificateSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyVaultCertificateSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultCertificateSyncSpec) DeepCopyInto(out *KeyVaultCertificateSyncSpec) {
	*out = *in
	out.Source = in.Source
	out.KeyVault = in.KeyVault
	if in.SyncPolicy != nil {
		in, out := &in.SyncPolicy, &out.SyncPolicy
		*out = new(SyncPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultCertificateSyncSpec.
func (in *KeyVaultCertificateSyncSpec) DeepCopy() *KeyVaultCertificateSyncSpec {
	if in == nil {
		return nil
	}
	out := new(KeyVaultCertificateSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultCertificateSyncStatus) DeepCopyInto(out *KeyVaultCertificateSyncStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultCertificateSyncStatus.
func (in *KeyVaultCertificateSyncStatus) DeepCopy() *KeyVaultCertificateSyncStatus {
	if in == nil {
		return nil
	}
	out := new(KeyVaultCertificateSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultSpec) DeepCopyInto(out *KeyVaultSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultSpec.
func (in *KeyVaultSpec) DeepCopy() *KeyVaultSpec {
	if in == nil {
		return nil
	}
	out := new(KeyVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerGuidance) DeepCopyInto(out *ListenerGuidance) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerGuidance.
func (in *ListenerGuidance) DeepCopy() *ListenerGuidance {
	if in == nil {
		return nil
	}
	out := new(ListenerGuidance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannedCertificate) DeepCopyInto(out *PlannedCertificate) {
	*out = *in
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannedCertificate.
func (in *PlannedCertificate) DeepCopy() *PlannedCertificate {
	if in == nil {
		return nil
	}
	out := new(PlannedCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkippedHost) DeepCopyInto(out *SkippedHost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkippedHost.
func (in *SkippedHost) DeepCopy() *SkippedHost {
	if in == nil {
		return nil
	}
	out := new(SkippedHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicySpec) DeepCopyInto(out *SyncPolicySpec) {
	*out = *in
	if in.ResyncInterval != nil {
		in, out := &in.ResyncInterval, &out.ResyncInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicySpec.
func (in *SyncPolicySpec) DeepCopy() *SyncPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SyncPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WildcardCertificatePolicy) DeepCopyInto(out *WildcardCertificatePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WildcardCertificatePolicy.
func (in *WildcardCertificatePolicy) DeepCopy() *WildcardCertificatePolicy {
	if in == nil {
		return nil
	}
	out := new(WildcardCertificatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WildcardCertificatePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WildcardCertificatePolicyList) DeepCopyInto(out *WildcardCertificatePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WildcardCertificatePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WildcardCertificatePolicyList.
func (in *WildcardCertificatePolicyList) DeepCopy() *WildcardCertificatePolicyList {
	if in == nil {
		return nil
	}
	out := new(WildcardCertificatePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WildcardCertificatePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WildcardCertificatePolicySpec) DeepCopyInto(out *WildcardCertificatePolicySpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(DiscoverySpec)
		(*in).DeepCopyInto(*out)
	}
	out.IssuerRef = in.IssuerRef
	out.KeyVault = in.KeyVault
	if in.SyncPolicy != nil {
		in, out := &in.SyncPolicy, &out.SyncPolicy
		*out = new(SyncPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WildcardCertificatePolicySpec.
func (in *WildcardCertificatePolicySpec) DeepCopy() *WildcardCertificatePolicySpec {
	if in == nil {
		return nil
	}
	out := new(WildcardCertificatePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WildcardCertificatePolicyStatus) DeepCopyInto(out *WildcardCertificatePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequiredCertificates != nil {
		in, out := &in.RequiredCertificates, &out.RequiredCertificates
		*out = make([]PlannedCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SkippedHosts != nil {
		in, out := &in.SkippedHosts, &out.SkippedHosts
		*out = make([]SkippedHost, len(*in))
		copy(*out, *in)
	}
	if in.ApplicationGateway != nil {
		in, out := &in.ApplicationGateway, &out.ApplicationGateway
		*out = new(ApplicationGatewayGuidance)
		(*in).DeepCopyInto(*out)
	}
	if in.LastDiscoveryTime != nil {
		in, out := &in.LastDiscoveryTime, &out.LastDiscoveryTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WildcardCertificatePolicyStatus.
func (in *WildcardCertificatePolicyStatus) DeepCopy() *WildcardCertificatePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(WildcardCertificatePolicyStatus)
	in.DeepCopyInto(out)
	return out
}
