// Command helmrbac renders the Helm chart's RBAC rules from the manifests under
// config/rbac.
//
// The chart used to keep its own hand-written copy of the ClusterRole, and that
// copy drifted: a +kubebuilder:rbac marker added so the operator could watch
// Gateways reached config/rbac/role.yaml but not the chart. A Helm-installed
// operator therefore had no permission to list Gateways, its cache never
// synced, and the manager exited -- on exactly the clusters the feature was
// added for. The CRDs never had that problem, because "make helm-crds" copies
// them and CI fails on the diff. This gives the rules the same treatment.
//
// Run it through "make helm-rbac". "make check-helm-manifests" fails if what is
// committed no longer matches what this produces.
package main

import (
	"bufio"
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"reflect"
	"slices"

	rbacv1 "k8s.io/api/rbac/v1"
	utilyaml "k8s.io/apimachinery/pkg/util/yaml"
	"sigs.k8s.io/yaml"
)

// source maps one role under config/rbac onto the named template the chart
// includes in its place.
type source struct {
	// template is the Helm template name, referenced from rbac.yaml.
	template string
	// file, kind and name locate exactly one role. Matching on all three means
	// a renamed or re-ordered document fails loudly instead of silently
	// rendering an empty rule set.
	file string
	kind string
	name string
	note string
}

var sources = []source{
	{
		template: "keyvault-certoperator.managerRules",
		file:     "config/rbac/role.yaml",
		kind:     "ClusterRole",
		name:     "manager-role",
		note:     "The operator's own permissions, from the +kubebuilder:rbac markers.",
	},
	{
		template: "keyvault-certoperator.metricsAuthRules",
		file:     "config/rbac/metrics_auth_role.yaml",
		kind:     "ClusterRole",
		name:     "metrics-auth-role",
		note:     "What the metrics endpoint needs to authenticate and authorize a scraper.",
	},
	{
		template: "keyvault-certoperator.leaderElectionRules",
		file:     "config/rbac/leader_election_role.yaml",
		kind:     "Role",
		name:     "leader-election-role",
		note:     "Namespaced, and only granted when leader election is turned on.",
	},
}

const header = `{{/*
Generated by "make helm-rbac" from config/rbac. Do not edit.

Editing these rules here rather than at the +kubebuilder:rbac markers they come
from is what let the chart fall behind the operator once already.
*/}}
`

func main() {
	out := flag.String("o", "", "file to write the rendered templates to")
	verify := flag.String("verify", "",
		"rendered chart manifest to check, instead of generating: every rule in config/rbac "+
			"must appear in it")
	flag.Parse()

	var err error
	switch {
	case *verify != "":
		err = check(*verify)
	default:
		err = generate(*out)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "helmrbac:", err)
		os.Exit(1)
	}
}

func generate(out string) error {
	if out == "" {
		return errors.New("-o is required")
	}

	var buf bytes.Buffer
	buf.WriteString(header)
	for _, src := range sources {
		rules, err := rulesFrom(src)
		if err != nil {
			return err
		}
		encoded, err := yaml.Marshal(rules)
		if err != nil {
			return fmt.Errorf("encoding %s: %w", src.template, err)
		}
		fmt.Fprintf(&buf, "\n{{/* %s */}}\n", src.note)
		fmt.Fprintf(&buf, "{{- define %q -}}\n", src.template)
		buf.Write(bytes.TrimRight(encoded, "\n"))
		buf.WriteString("\n{{- end }}\n")
	}

	// Written in one go, after every source has parsed, so a failure leaves the
	// committed file intact rather than truncated.
	if err := os.WriteFile(out, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", out, err)
	}
	return nil
}

// check asserts that a rendered chart really grants what config/rbac says.
//
// The staleness gate on the generated file cannot see this: deleting the
// include from rbac.yaml, or wrapping it in a values guard, leaves the
// generated file untouched and the rendered ClusterRole short. That is the same
// failure as the drift it replaced, so it is checked against the rendered
// output rather than the template.
func check(manifest string) error {
	rendered, err := allRules(manifest)
	if err != nil {
		return err
	}
	for _, src := range sources {
		// Leader election and metrics are optional by design, so only the
		// operator's own permissions are required to be present.
		if src.template != "keyvault-certoperator.managerRules" {
			continue
		}
		want, err := rulesFrom(src)
		if err != nil {
			return err
		}
		for _, rule := range want {
			if !slices.ContainsFunc(rendered, func(got rbacv1.PolicyRule) bool {
				return reflect.DeepEqual(got, rule)
			}) {
				encoded, _ := yaml.Marshal([]rbacv1.PolicyRule{rule})
				return fmt.Errorf(
					"the rendered chart in %s does not grant this rule from %s:\n%s"+
						"run 'make helm-rbac', and check that rbac.yaml still includes %q",
					manifest, src.file, encoded, src.template)
			}
		}
	}
	return nil
}

// allRules collects the rules of every Role and ClusterRole in a manifest.
func allRules(manifest string) ([]rbacv1.PolicyRule, error) {
	var out []rbacv1.PolicyRule
	err := eachDocument(manifest, func(doc document) bool {
		if doc.Kind == "ClusterRole" || doc.Kind == "Role" {
			out = append(out, doc.Rules...)
		}
		return false
	})
	if err != nil {
		return nil, err
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s contains no Role or ClusterRole at all", manifest)
	}
	return out, nil
}

// document is the part of a Role or ClusterRole this needs. Decoding into
// rbacv1.PolicyRule rather than a free-form map means a malformed rule is
// rejected here instead of by the API server at install time.
type document struct {
	Kind     string `json:"kind"`
	Metadata struct {
		Name string `json:"name"`
	} `json:"metadata"`
	Rules []rbacv1.PolicyRule `json:"rules"`
}

func rulesFrom(src source) ([]rbacv1.PolicyRule, error) {
	// Matching on file, kind and name together means a renamed or re-ordered
	// document fails loudly instead of silently rendering an empty rule set.
	var found []rbacv1.PolicyRule
	err := eachDocument(src.file, func(doc document) bool {
		if doc.Kind != src.kind || doc.Metadata.Name != src.name {
			return false
		}
		found = doc.Rules
		return true
	})
	if err != nil {
		return nil, err
	}
	if found == nil {
		return nil, fmt.Errorf("no %s named %q in %s", src.kind, src.name, src.file)
	}
	if len(found) == 0 {
		return nil, fmt.Errorf("%s %s in %s has no rules", src.kind, src.name, src.file)
	}
	return found, nil
}

// eachDocument calls visit for every YAML document in path, stopping early when
// visit reports that it has what it needs.
func eachDocument(path string, visit func(document) bool) error {
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("opening %s: %w", path, err)
	}
	defer file.Close() //nolint:errcheck // read-only

	reader := utilyaml.NewYAMLReader(bufio.NewReader(file))
	for {
		raw, err := reader.Read()
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}
		if len(bytes.TrimSpace(raw)) == 0 {
			continue
		}

		// Deliberately not strict: these files also hold the binding
		// documents, whose fields this struct does not model.
		var doc document
		if err := yaml.Unmarshal(raw, &doc); err != nil {
			return fmt.Errorf("decoding a document in %s: %w", path, err)
		}
		if visit(doc) {
			return nil
		}
	}
}
