{{/*
Generated by "make helm-rbac" from config/rbac. Do not edit.

Editing these rules here rather than at the +kubebuilder:rbac markers they come
from is what let the chart fall behind the operator once already.
*/}}

{{/* The operator's own permissions, from the +kubebuilder:rbac markers. */}}
{{- define "keyvault-certoperator.managerRules" -}}
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certsync.vileend.io
  resources:
  - keyvaultcertificatesyncs
  - wildcardcertificatepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certsync.vileend.io
  resources:
  - keyvaultcertificatesyncs/finalizers
  - wildcardcertificatepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - certsync.vileend.io
  resources:
  - keyvaultcertificatesyncs/status
  - wildcardcertificatepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
{{- end }}

{{/* What the metrics endpoint needs to authenticate and authorize a scraper. */}}
{{- define "keyvault-certoperator.metricsAuthRules" -}}
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end }}

{{/* Namespaced, and only granted when leader election is turned on. */}}
{{- define "keyvault-certoperator.leaderElectionRules" -}}
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
{{- end }}
